apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APPNAME>
  namespace: <NAMESPACE-NAME>
  labels:
    app: <APPNAME>
spec:
  replicas: 2
  selector:
    matchLabels:
      app: <APPNAME>
  template:
    metadata:
      labels:
        app: <APPNAME>
    spec:
      imagePullSecrets:
        - name: myregistrykey
      containers:
        - name: <APPNAME>
          image: <CONTAINER_REGISTRY>/yeeorder/<APPNAME>:<BUILD_TAG>
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: <APPNAME>-svc
  namespace: <NAMESPACE-NAME>
  labels:
    app: <APPNAME>-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      name: <APPNAME>
  selector:
    app: <APPNAME>
  type: ClusterIP
